In [26]:
import requests
from IPython.core.display import HTML
#HTML(f"""
#<style>
#@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
#</style>
#""")

# Linear Algebra using Python and Numpy
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to familiarise yourself with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---

In [29]:
difference = A - B
print(difference)


[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]



---
**Task 2 (easy): Multiplication properties👩‍💻**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.


---

In [30]:
# Write your solution here
##Reason why different: matrix multiplication is not commutative, 𝐴𝐶  will generally not be equal to 𝐶𝐴

# Calculate AC and CA using np.dot
AC_dot = np.dot(A, C)
CA_dot = np.dot(C, A)

# Calculate AC and CA using @ operator
AC_at = A @ C
CA_at = C @ A

# Print the results
print("AC using np.dot:\n", AC_dot)
print("\nCA using np.dot:\n", CA_dot)

print("\nAC using @ operator:\n", AC_at)
print("\nCA using @ operator:\n", CA_at)

AC using np.dot:
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]

CA using np.dot:
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]

AC using @ operator:
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]

CA using @ operator:
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]



---
**Task 3 (easy): Elementwise multiplication👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.


---

In [31]:
# Write your solution here

# Elementwise multiplication of A and C using *
elementwise_multiplication = A * C

# Print the result
print("Elementwise multiplication of A and C:\n", elementwise_multiplication)


Elementwise multiplication of A and C:
 [[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]



---
**Task 4 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. _Hint: The question relates to the limitations of floating point numbers._


---

In [32]:
# Write your solution here

I = np.eye
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)

# Verify that AA^-1 = I and CC^-1 = I
I_A = np.dot(A, A_inv)
I_C = np.dot(C, C_inv)

# Print the results
print("A * A_inv:\n", I_A)
print("\nC * C_inv:\n", I_C)

identity_matrix = np.eye(A.shape[0]) # A is a square matrix, so we can use A.shape[0] to get the number of rows/columns
# Check if they are approximately the identity matrix
print("\nIs A * A_inv approximately I?", np.allclose(I_A, identity_matrix))
print("\nIs C * C_inv approximately I?", np.allclose(I_C, identity_matrix))


A * A_inv:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.43769499e-16  1.00000000e+00 -9.21041021e-14  7.65609798e-14]
 [ 2.47949809e-15 -1.55431223e-14  1.00000000e+00 -4.48530102e-14]
 [ 1.11022302e-15 -2.95636531e-14  1.70657139e-14  1.00000000e+00]]

C * C_inv:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 7.23865412e-15  1.00000000e+00 -3.00781622e-13 -2.62012634e-15]
 [-1.66533454e-14  4.01283944e-14  1.00000000e+00  7.77156117e-15]
 [-1.66533454e-14  4.01283944e-14 -3.88701417e-13  1.00000000e+00]]

Is A * A_inv approximately I? True

Is C * C_inv approximately I? True


### Properties

---
**Task 5 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---

In [33]:
#1:
D_inv_E_inv = np.dot(D_inv, E_inv)
E_D_inv = np.linalg.inv(np.dot(E, D))
print("\nIs D_inv * E_inv approximately (ED)_inv?", np.allclose(D_inv_E_inv, E_D_inv))

#2:
D_E_inv = np.linalg.inv(np.dot(D, E))
print("\nIs D_inv * E_inv approximately (ED)_inv?", np.allclose(D_inv_E_inv, D_E_inv))



Is D_inv * E_inv approximately (ED)_inv? True

Is D_inv * E_inv approximately (ED)_inv? False



---
**Task 6 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Based on the results, determine which of the matrices have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-6>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---

In [34]:
# Determinants:
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)

# Print the determinants
print("Determinant of A:", det_A)
print("Determinant of B:", det_B)
print("Determinant of C:", det_C)

#They only have inverses if determinant is not equal to 0, therefore:
#A and C have inverses, B does not have an inverse

Determinant of A: 1.6534391534392967e-07
Determinant of B: 0.0
Determinant of C: 1.0498026371042581e-07



---
**Task 7 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.


---

In [35]:
# Write your solution here

# Transpose of inverse D
D_inv_T = D_inv.T

# Inverse of transpose D
D_T_inv = np.linalg.inv(D.T)


print("Are they equal", np.allclose(D_inv_T, D_T_inv))

Are they equal True


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 8 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$

---

In [41]:
Matrix_A = np.array([
    [2, 3],
    [1, 1]
])

det_Matrix_A = np.linalg.det(Matrix_A)
print("Determinant of Matrix_A:", det_Matrix_A)

Matrix_B = np.array([
    [1, 0],
    [0, 1]
])
det_Matrix_B = np.linalg.det(Matrix_B)
print("Determinant of Matrix_B:", det_Matrix_B)

#NÅEDE HERTIL.

Matrix_C = np.array([
    [1, 2],
    [3, 4]
])
det_Matrix_C = np.linalg.det(Matrix_C)
print("Determinant of Matrix_C:", det_Matrix_C)

Matrix_D = np.array([
    [4, 7],
    [2, 6]
])
det_Matrix_D = np.linalg.det(Matrix_D)
print("Determinant of Matrix_D:", det_Matrix_D)

Matrix_E = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
det_Matrix_E = np.linalg.det(Matrix_E)
print("Determinant of Matrix_E:", det_Matrix_E)

Matrix_F = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
det_Matrix_F = np.linalg.det(Matrix_F)
print("Determinant of Matrix_F:", det_Matrix_F)

Determinant of Matrix_A: -1.0
Determinant of Matrix_B: 1.0


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 9 (medium): Implementing matrix multiplication _(optional)_👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.


---

In [54]:
def matmul(a, b):
    N = a.shape[0]
    D = a.shape[1]
    K = b.shape[1]

    result = np.zeros((N, K))

    #Formula says, that result at index i,j is the sum of a[i, d] * b[d, j] for all d in range(D)
    for i in range(N):
        for j in range(K):
            sum = 0
            for d in range(D):
                sum += a[i, d] * b[d, j]
            result[i, j] = sum
    return result
        

ma = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

mb = np.array([
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
])

result = matmul(ma, mb)
print("Matrix multiplication result:\n", result)

result2 = np.matmul(ma, mb)
print("Matrix multiplication result2:\n", result2)

#Is equal:
print("Are they equal?", np.allclose(result, result2))

Matrix multiplication result:
 [[ 33.   6.  26.]
 [ 78.  21.  77.]
 [123.  36. 128.]]
Matrix multiplication result2:
 [[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]
Are they equal? True


---
